"""全局常量定义"""
CONTEXT_BUDGET = 32_000
AVG_CHARS_PER_TOKEN = 4

BLOCKED_SQL_STATEMENTS = {"DROP", "DELETE", "ALTER", "TRUNCATE", "INSERT", "UPDATE", "CREATE"}
BLOCKED_SQL_FUNCTIONS = {"SLEEP", "BENCHMARK", "LOAD_FILE"}

MAX_SQL_ROWS = 10_000
SQL_TIMEOUT_SECONDS = 10

EMBEDDING_MODEL = "paraphrase-multilingual-MiniLM-L12-v2"
RERANKER_MODEL = "BAAI/bge-reranker-base"

CATALOG_SEARCH_HIGH_THRESHOLD = 0.45
CATALOG_SEARCH_MEDIUM_THRESHOLD = 0.30
CATALOG_COLUMN_LIMIT = 20
